### ISSUE TITLE
Errors on some devices

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/softwareupdate#17]
```
softwareupdate Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/softwareupdate", line 450, in <module>
    main()
  File "/usr/local/munkireport/scripts/softwareupdate", line 434, in main
    result.update(get_ddm_info())
  File "/usr/local/munkireport/scripts/softwareupdate", line 306, in get_ddm_info
    if plist["SUCorePersistedStatePolicyFields"] and plist["SUCorePersistedStatePolicyFields"]["Declarations"]:
  File "/Library/ManagedFrameworks/Python/Python3.framework/Versions/3.10/lib/python3.10/site-packages/objc/_convenience_mapping.py", line 18, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "/Library/ManagedFrameworks/Python/Python3.framework/Versions/3.10/lib/python3.10/site-packages/objc/_convenience.py", line 134, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'Declarations'
```

and 

```
defaults read /private/var/db/softwareupdate/SoftwareUpdateDDMStatePersistence.plist SUCorePersistedStatePolicyFields
{
    SUCoreDDMDeclarationGlobalSettings =     {
        adminInstallRequired = 0;
        enableGlobalNotifications = 1;
        serializedKeys =         (
            "com.apple.RemoteManagement.SoftwareUpdateExtension.GlobalSettings/E44A9551-9090-4678-4459-23E431F57BAF:NEEzNDQyNkUtOEEzMi01NzJFLUJBREItWEIwQ0JCtUIz4DU1.N2U0Y2VlN2UtODI1YS01OWEzLTk3NWEtZDgwNTr1NjNjYvFi"
        );
    };
}
```

**Comment by tuxudo** [comment]
Fixed in v3.7 of the module.
